name: Generate ASCII Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay
      run: sudo apt-get install cowsay -y

    - name: Run dragon
      run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR" >> dragon.txt

    - name: Sleep for 10 seconds
      run: sleep 10

  build_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 10 seconds
      run: sleep 10

    - name: Test file exists
      run: grep -i "dragon" dragon.txt

  build_job_3:
    needs: build_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Read file
      run: cat dragon.txt
    - name: Deploying
      run: echo "deploying"





