name: Generate ASCII Artwork

on: push

jobs:
    ascii_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Exec shell script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh
